//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biklas_API_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alertas
    {
        public int IdAlerta { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTimeOffset FechaHora { get; set; }
        public int IdSegmento { get; set; }
    
        public virtual Segmentos Segmentos { get; set; }
    }
}
