//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biklas_API_V2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BiklasEntities : DbContext
    {
        public BiklasEntities()
            : base("name=BiklasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccionEntidad> AccionEntidad { get; set; }
        public virtual DbSet<Acciones> Acciones { get; set; }
        public virtual DbSet<Alertas> Alertas { get; set; }
        public virtual DbSet<Amigos> Amigos { get; set; }
        public virtual DbSet<Aristas> Aristas { get; set; }
        public virtual DbSet<Entidades> Entidades { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Rutas> Rutas { get; set; }
        public virtual DbSet<Segmentos> Segmentos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Vertices> Vertices { get; set; }
        public virtual DbSet<Vias> Vias { get; set; }
    }
}
