//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biklas_API_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rutas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rutas()
        {
            this.Segmentos = new HashSet<Segmentos>();
        }
    
        public int IdRuta { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> PosicionInicioX { get; set; }
        public Nullable<decimal> PosicionInicioY { get; set; }
        public Nullable<decimal> PosicionFinX { get; set; }
        public Nullable<decimal> PosicionFinY { get; set; }
        public Nullable<System.DateTimeOffset> TiempoInicio { get; set; }
        public Nullable<System.DateTimeOffset> TiempoFin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Segmentos> Segmentos { get; set; }
    }
}
